import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedGamification() {
  console.log('🌱 Seeding gamification data...');

  // ====================
  // DAILY TASKS (7 tasks)
  // ====================
  
  const dailyTasks = [
    {
      taskId: 'daily_login',
      name: '🔥 Ежедневный вход',
      nameEn: '🔥 Daily Login',
      description: 'Зайдите в приложение',
      descriptionEn: 'Log into the app',
      type: 'LOGIN',
      target: 1,
      rewardXp: 5,
      rewardTon: 0,
      sortOrder: 1,
    },
    {
      taskId: 'buy_1_ticket',
      name: '🎫 Купить билет',
      nameEn: '🎫 Buy a Ticket',
      description: 'Купите 1 билет',
      descriptionEn: 'Buy 1 ticket',
      type: 'BUY_TICKETS',
      target: 1,
      rewardXp: 10,
      rewardTon: 0,
      sortOrder: 2,
    },
    {
      taskId: 'buy_3_tickets',
      name: '🎫 Купить 3 билета',
      nameEn: '🎫 Buy 3 Tickets',
      description: 'Купите 3 билета за день',
      descriptionEn: 'Buy 3 tickets in a day',
      type: 'BUY_TICKETS',
      target: 3,
      rewardXp: 20,
      rewardTon: 0,
      sortOrder: 3,
    },
    {
      taskId: 'buy_5_tickets',
      name: '🎫 Купить 5 билетов',
      nameEn: '🎫 Buy 5 Tickets',
      description: 'Купите 5 билетов за день',
      descriptionEn: 'Buy 5 tickets in a day',
      type: 'BUY_TICKETS',
      target: 5,
      rewardXp: 30,
      rewardTon: 0.05,
      sortOrder: 4,
    },
    {
      taskId: 'invite_friend',
      name: '👥 Пригласить друга',
      nameEn: '👥 Invite a Friend',
      description: 'Пригласите друга по реферальной ссылке',
      descriptionEn: 'Invite a friend via referral link',
      type: 'REFERRAL',
      target: 1,
      rewardXp: 30,
      rewardTon: 0.1,
      sortOrder: 5,
    },
    {
      taskId: 'check_results',
      name: '🏆 Проверить результаты',
      nameEn: '🏆 Check Results',
      description: 'Посмотрите результаты розыгрыша',
      descriptionEn: 'Check draw results',
      type: 'CHECK_RESULTS',
      target: 1,
      rewardXp: 3,
      rewardTon: 0,
      sortOrder: 6,
    },
    {
      taskId: 'streak_7_days',
      name: '🔄 7 дней подряд',
      nameEn: '🔄 7-Day Streak',
      description: 'Заходите 7 дней подряд',
      descriptionEn: 'Log in 7 days in a row',
      type: 'STREAK',
      target: 7,
      rewardXp: 50,
      rewardTon: 0,
      sortOrder: 7,
    },
  ];

  for (const task of dailyTasks) {
    await prisma.dailyTask.upsert({
      where: { taskId: task.taskId },
      update: task,
      create: task,
    });
  }

  console.log('✅ Created 7 daily tasks');

  // ====================
  // QUESTS (for Quest model)
  // ====================

  const quests = [
    // Daily quests
    {
      slug: 'daily_first_ticket',
      title: 'Первый билет дня',
      description: 'Купите первый билет сегодня',
      type: 'daily',
      category: 'tickets',
      target: 1,
      rewardType: 'xp',
      rewardValue: 10,
      sortOrder: 1,
    },
    {
      slug: 'daily_three_tickets',
      title: 'Три билета',
      description: 'Купите 3 билета за день',
      type: 'daily',
      category: 'tickets',
      target: 3,
      rewardType: 'xp',
      rewardValue: 25,
      sortOrder: 2,
    },
    {
      slug: 'daily_check_in',
      title: 'Ежедневная отметка',
      description: 'Сделайте check-in сегодня',
      type: 'daily',
      category: 'streak',
      target: 1,
      rewardType: 'xp',
      rewardValue: 5,
      sortOrder: 3,
    },
    // Weekly quests
    {
      slug: 'weekly_10_tickets',
      title: '10 билетов за неделю',
      description: 'Купите 10 билетов за неделю',
      type: 'weekly',
      category: 'tickets',
      target: 10,
      rewardType: 'xp',
      rewardValue: 100,
      sortOrder: 10,
    },
    {
      slug: 'weekly_streak_7',
      title: 'Неделя подряд',
      description: 'Заходите 7 дней подряд',
      type: 'weekly',
      category: 'streak',
      target: 7,
      rewardType: 'ticket',
      rewardValue: 1,
      sortOrder: 11,
    },
    {
      slug: 'weekly_invite',
      title: 'Пригласите друга',
      description: 'Пригласите 1 друга на этой неделе',
      type: 'weekly',
      category: 'social',
      target: 1,
      rewardType: 'xp',
      rewardValue: 50,
      sortOrder: 12,
    },
    // Onetime quests (onboarding)
    {
      slug: 'onboarding_first_ticket',
      title: 'Первый билет',
      description: 'Купите свой первый билет',
      type: 'onetime',
      category: 'onboarding',
      target: 1,
      rewardType: 'xp',
      rewardValue: 20,
      sortOrder: 100,
    },
    {
      slug: 'onboarding_connect_wallet',
      title: 'Подключите кошелёк',
      description: 'Подключите TON кошелёк',
      type: 'onetime',
      category: 'onboarding',
      target: 1,
      rewardType: 'xp',
      rewardValue: 15,
      sortOrder: 101,
    },
    {
      slug: 'onboarding_first_referral',
      title: 'Первый реферал',
      description: 'Пригласите первого друга',
      type: 'onetime',
      category: 'onboarding',
      target: 1,
      rewardType: 'ticket',
      rewardValue: 1,
      sortOrder: 102,
    },
  ];

  for (const quest of quests) {
    await prisma.quest.upsert({
      where: { slug: quest.slug },
      update: quest,
      create: quest,
    });
  }

  console.log('✅ Created 9 quests');

  // ====================
  // ACHIEVEMENTS (24 achievements in 6 categories)
  // Schema fields: tier is Int, target (not requirement), type, rarity
  // ====================

  const achievements = [
    // TICKETS Category (5 achievements)
    {
      slug: 'first_ticket',
      name: '🎫 Первый билет',
      nameEn: '🎫 First Ticket',
      title: 'Первый билет',
      description: 'Купите первый билет в лотерею',
      descriptionEn: 'Buy your first lottery ticket',
      category: 'tickets',
      type: 'progress',
      target: 1,
      tier: 1, // bronze
      rarity: 'COMMON',
      icon: '🎫',
      rewardXp: 10,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 1,
    },
    {
      slug: 'player',
      name: '🎯 Игрок',
      nameEn: '🎯 Player',
      title: 'Игрок',
      description: 'Купите 10 билетов',
      descriptionEn: 'Buy 10 tickets',
      category: 'tickets',
      type: 'progress',
      target: 10,
      tier: 1,
      rarity: 'COMMON',
      icon: '🎯',
      rewardXp: 50,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 2,
    },
    {
      slug: 'collector',
      name: '🎰 Коллекционер',
      nameEn: '🎰 Collector',
      title: 'Коллекционер',
      description: 'Купите 50 билетов',
      descriptionEn: 'Buy 50 tickets',
      category: 'tickets',
      type: 'progress',
      target: 50,
      tier: 2,
      rarity: 'RARE',
      icon: '🎰',
      rewardXp: 100,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 3,
    },
    {
      slug: 'maniac',
      name: '🎲 Маньяк',
      nameEn: '🎲 Maniac',
      title: 'Маньяк',
      description: 'Купите 100 билетов',
      descriptionEn: 'Buy 100 tickets',
      category: 'tickets',
      type: 'progress',
      target: 100,
      tier: 2,
      rarity: 'RARE',
      icon: '🎲',
      rewardXp: 200,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 4,
    },
    {
      slug: 'lottery_legend',
      name: '👑 Легенда лотереи',
      nameEn: '👑 Lottery Legend',
      title: 'Легенда лотереи',
      description: 'Купите 500 билетов',
      descriptionEn: 'Buy 500 tickets',
      category: 'tickets',
      type: 'progress',
      target: 500,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '👑',
      rewardXp: 500,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 5,
    },

    // WINS Category (4 achievements)
    {
      slug: 'first_win',
      name: '🎉 Первая победа',
      nameEn: '🎉 First Win',
      title: 'Первая победа',
      description: 'Выиграйте первый раз',
      descriptionEn: 'Win for the first time',
      category: 'wins',
      type: 'progress',
      target: 1,
      tier: 1,
      rarity: 'COMMON',
      icon: '🎉',
      rewardXp: 20,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 6,
    },
    {
      slug: 'lucky',
      name: '🍀 Везунчик',
      nameEn: '🍀 Lucky',
      title: 'Везунчик',
      description: 'Выиграйте 5 раз',
      descriptionEn: 'Win 5 times',
      category: 'wins',
      type: 'progress',
      target: 5,
      tier: 1,
      rarity: 'COMMON',
      icon: '🍀',
      rewardXp: 50,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 7,
    },
    {
      slug: 'fortune',
      name: '💰 Фортуна',
      nameEn: '💰 Fortune',
      title: 'Фортуна',
      description: 'Выиграйте 25 раз',
      descriptionEn: 'Win 25 times',
      category: 'wins',
      type: 'progress',
      target: 25,
      tier: 2,
      rarity: 'RARE',
      icon: '💰',
      rewardXp: 150,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 8,
    },
    {
      slug: 'jackpot_winner',
      name: '💎 Джекпот',
      nameEn: '💎 Jackpot Winner',
      title: 'Джекпот',
      description: 'Выиграйте 100 раз',
      descriptionEn: 'Win 100 times',
      category: 'wins',
      type: 'progress',
      target: 100,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '💎',
      rewardXp: 500,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 9,
    },

    // STREAK Category (4 achievements)
    {
      slug: 'week_streak',
      name: '🔥 Неделя подряд',
      nameEn: '🔥 Week Streak',
      title: 'Неделя подряд',
      description: 'Серия входов 7 дней подряд',
      descriptionEn: '7-day login streak',
      category: 'streak',
      type: 'progress',
      target: 7,
      tier: 1,
      rarity: 'COMMON',
      icon: '🔥',
      rewardXp: 30,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 10,
    },
    {
      slug: 'two_weeks_streak',
      name: '⚡ Две недели',
      nameEn: '⚡ Two Weeks',
      title: 'Две недели',
      description: 'Серия входов 14 дней подряд',
      descriptionEn: '14-day login streak',
      category: 'streak',
      type: 'progress',
      target: 14,
      tier: 1,
      rarity: 'COMMON',
      icon: '⚡',
      rewardXp: 70,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 11,
    },
    {
      slug: 'month_streak',
      name: '🌟 Месяц подряд',
      nameEn: '🌟 Month Streak',
      title: 'Месяц подряд',
      description: 'Серия входов 30 дней подряд',
      descriptionEn: '30-day login streak',
      category: 'streak',
      type: 'progress',
      target: 30,
      tier: 2,
      rarity: 'EPIC',
      icon: '🌟',
      rewardXp: 200,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 12,
    },
    {
      slug: 'veteran',
      name: '💪 Ветеран',
      nameEn: '💪 Veteran',
      title: 'Ветеран',
      description: 'Серия входов 100 дней подряд',
      descriptionEn: '100-day login streak',
      category: 'streak',
      type: 'progress',
      target: 100,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '💪',
      rewardXp: 1000,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 13,
    },

    // REFERRAL Category (4 achievements)
    {
      slug: 'first_friend',
      name: '👋 Первый друг',
      nameEn: '👋 First Friend',
      title: 'Первый друг',
      description: 'Пригласите первого друга',
      descriptionEn: 'Invite your first friend',
      category: 'referrals',
      type: 'progress',
      target: 1,
      tier: 1,
      rarity: 'COMMON',
      icon: '👋',
      rewardXp: 20,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 14,
    },
    {
      slug: 'social',
      name: '👥 Социальный',
      nameEn: '👥 Social',
      title: 'Социальный',
      description: 'Пригласите 5 друзей',
      descriptionEn: 'Invite 5 friends',
      category: 'referrals',
      type: 'progress',
      target: 5,
      tier: 1,
      rarity: 'COMMON',
      icon: '👥',
      rewardXp: 100,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 15,
    },
    {
      slug: 'ambassador',
      name: '🎯 Амбассадор',
      nameEn: '🎯 Ambassador',
      title: 'Амбассадор',
      description: 'Пригласите 20 друзей',
      descriptionEn: 'Invite 20 friends',
      category: 'referrals',
      type: 'progress',
      target: 20,
      tier: 2,
      rarity: 'RARE',
      icon: '🎯',
      rewardXp: 300,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 16,
    },
    {
      slug: 'influencer',
      name: '🌐 Инфлюенсер',
      nameEn: '🌐 Influencer',
      title: 'Инфлюенсер',
      description: 'Пригласите 100 друзей',
      descriptionEn: 'Invite 100 friends',
      category: 'referrals',
      type: 'progress',
      target: 100,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '🌐',
      rewardXp: 1000,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 17,
    },

    // LEVEL Category (3 achievements)
    {
      slug: 'level_5',
      name: '⬆️ Уровень 5',
      nameEn: '⬆️ Level 5',
      title: 'Уровень 5',
      description: 'Достигните 5 уровня',
      descriptionEn: 'Reach level 5',
      category: 'level',
      type: 'milestone',
      target: 5,
      tier: 1,
      rarity: 'COMMON',
      icon: '⬆️',
      rewardXp: 50,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 18,
    },
    {
      slug: 'level_10',
      name: '🎖️ Уровень 10',
      nameEn: '🎖️ Level 10',
      title: 'Уровень 10',
      description: 'Достигните 10 уровня',
      descriptionEn: 'Reach level 10',
      category: 'level',
      type: 'milestone',
      target: 10,
      tier: 2,
      rarity: 'RARE',
      icon: '🎖️',
      rewardXp: 100,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 19,
    },
    {
      slug: 'level_25',
      name: '🏅 Уровень 25',
      nameEn: '🏅 Level 25',
      title: 'Уровень 25',
      description: 'Достигните 25 уровня',
      descriptionEn: 'Reach level 25',
      category: 'level',
      type: 'milestone',
      target: 25,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '🏅',
      rewardXp: 500,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 20,
    },

    // SPENDING Category (4 achievements)
    {
      slug: 'first_bet',
      name: '💵 Первая ставка',
      nameEn: '💵 First Bet',
      title: 'Первая ставка',
      description: 'Потратьте первый TON',
      descriptionEn: 'Spend your first TON',
      category: 'spending',
      type: 'progress',
      target: 1,
      tier: 1,
      rarity: 'COMMON',
      icon: '💵',
      rewardXp: 10,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 21,
    },
    {
      slug: 'spender',
      name: '💸 Транжира',
      nameEn: '💸 Spender',
      title: 'Транжира',
      description: 'Потратьте 10 TON',
      descriptionEn: 'Spend 10 TON',
      category: 'spending',
      type: 'progress',
      target: 10,
      tier: 1,
      rarity: 'COMMON',
      icon: '💸',
      rewardXp: 50,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 22,
    },
    {
      slug: 'highroller',
      name: '💎 Хайроллер',
      nameEn: '💎 High Roller',
      title: 'Хайроллер',
      description: 'Потратьте 100 TON',
      descriptionEn: 'Spend 100 TON',
      category: 'spending',
      type: 'progress',
      target: 100,
      tier: 2,
      rarity: 'EPIC',
      icon: '💎',
      rewardXp: 200,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 23,
    },
    {
      slug: 'whale',
      name: '🐋 Кит',
      nameEn: '🐋 Whale',
      title: 'Кит',
      description: 'Потратьте 1000 TON',
      descriptionEn: 'Spend 1000 TON',
      category: 'spending',
      type: 'progress',
      target: 1000,
      tier: 3,
      rarity: 'LEGENDARY',
      icon: '🐋',
      rewardXp: 1000,
      rewardTon: 0,
      rewardTickets: 0,
      sortOrder: 24,
    },
  ];

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { slug: achievement.slug },
      update: achievement,
      create: achievement,
    });
  }

  console.log('✅ Created 24 achievements');

  // ====================
  // REWARDS (templates)
  // ====================

  const rewards = [
    {
      slug: 'streak_7_bonus',
      name: 'Бонус за 7 дней',
      description: 'Награда за 7-дневную серию',
      type: 'streak_milestone',
      rewardType: 'xp',
      rewardValue: 50,
    },
    {
      slug: 'streak_14_bonus',
      name: 'Бонус за 14 дней',
      description: 'Награда за 14-дневную серию',
      type: 'streak_milestone',
      rewardType: 'xp',
      rewardValue: 100,
    },
    {
      slug: 'streak_30_bonus',
      name: 'Бонус за 30 дней',
      description: 'Награда за 30-дневную серию + бесплатный билет',
      type: 'streak_milestone',
      rewardType: 'ticket',
      rewardValue: 1,
    },
    {
      slug: 'level_up_bonus',
      name: 'Бонус за уровень',
      description: 'Награда за повышение уровня',
      type: 'level_up',
      rewardType: 'xp',
      rewardValue: 10,
    },
    {
      slug: 'referral_bonus',
      name: 'Реферальный бонус',
      description: 'Награда за приглашение друга',
      type: 'referral',
      rewardType: 'xp',
      rewardValue: 25,
    },
  ];

  for (const reward of rewards) {
    await prisma.reward.upsert({
      where: { slug: reward.slug },
      update: reward,
      create: reward,
    });
  }

  console.log('✅ Created 5 reward templates');

  console.log('\n🎉 Gamification data seeded successfully!');
  console.log('\n📊 Summary:');
  console.log('- 7 Daily Tasks');
  console.log('- 9 Quests (daily, weekly, onetime)');
  console.log('- 24 Achievements (6 categories):');
  console.log('  • TICKETS: 5 achievements');
  console.log('  • WINS: 4 achievements');
  console.log('  • STREAK: 4 achievements');
  console.log('  • REFERRALS: 4 achievements');
  console.log('  • LEVEL: 3 achievements');
  console.log('  • SPENDING: 4 achievements');
  console.log('- 5 Reward templates');
}

seedGamification()
  .catch((e) => {
    console.error('❌ Error seeding gamification data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
